### ISSUE TITLE
Request for USB Serial

### ISSUE THREAD

**Issue by edogaldo** [stm32duino/Arduino_Core_STM32#271] opened 2018-06-22 17:19 UTC
Possibly as external library..

Thanks in advance, E.

**Comment by fpistm** [comment] 2018-06-23 09:02
Duplicate of #222

**Closed** 2018-06-26 19:47 UTC
Labels: Duplicated

**Comment by davidanger** [comment] 2018-06-28 09:58
Hi,edogaldo
 you can using STlink Virtually Serial if you have one, as Ardiuno.
