### ISSUE TITLE
Pin name PXn should match Arduino pin numberin Dx

### ISSUE THREAD

**Issue by gus-ghielec** [stm32duino/Arduino_Core_STM32#81] opened 2017-08-15 23:47 UTC
I have an LED connected to D34(PC6). My code works when I use D34 just fine but then it doesn't work if I use PC6 instead of D34. Both of these should be the same thing. There seem to be an issue when using the processor pin names.

This is necessary for those building products based on the nucleo board and want to use the processor pin name instead of the "Arduino" Dxx pin names.

I am using the blink LED code example.

**Comment by fpistm** [comment] 2017-08-16 04:41
Hi @gus-ghielec,
PinName and pin numbering is different. Arduino API use the pin numbering (Dx). When using the PinName (Pxy) its value is not equal to the pin number.
To use the PinName instead of  pin numbering use:
`uint32_t pinNametoDigitalPin(PinName p);`

So, `digitalWrite(D34, HIGH);` and `digitalWrite(pinNametoDigitalPin(PC6), HIGH);` are the same.
but `digitalWrite(pinNametoDigitalPin(PC6), HIGH);` not

**Comment by rogerclarkmelbourne** [comment] 2017-08-16 06:28
@fpistm 
I think you mean


digitalWrite(PC6, HIGH); not

BTW. I was not aware that the direct mapping does not work using the pin names like it does in libmaple and STM32Generic

**Comment by fpistm** [comment] 2017-08-16 06:34
Thanks @rogerclarkmelbourne 
Yes, not the same pinmapping. It is based on mbed pinmap.

**Comment by rogerclarkmelbourne** [comment] 2017-08-16 06:45
If someone made their own variant file, do you think they could map as 1:1 ?

i.e I know @gus-ghielec sells a custom board, and I think it may have pin names rather than pin numbers

**Comment by Adminius** [comment] 2017-08-16 07:00
it would be great if we can use Pxy names without pinNametoDigitalPin

**Comment by fpistm** [comment] 2017-08-16 07:25
No @rogerclarkmelbourne  as PinName is not an index.
[PinNames.h#L33](https://github.com/stm32duino/Arduino_Core_STM32/blob/master/cores/arduino/stm32/PinNames.h#L33)
It encodes the GPIO port and pin number on 8bits

**Comment by rogerclarkmelbourne** [comment] 2017-08-16 09:42
Yikes

This is going to be a rather confusing for anyone using the Discovery series boards, which are labelled with Pxn format names

**Comment by RickKimball** [comment] 2017-08-16 16:15
The pinname issue is kind of embedded deeply in these cores at this point.

**Comment by fpistm** [comment] 2017-08-16 17:13
> @RickKimball  The pinname issue is kind of embedded deeply in these cores at this point.
I will not change the pinmap management but I could grant this request. I will do a PR before the end of the week. I hope ;)

**Comment by rogerclarkmelbourne** [comment] 2017-08-17 00:22
I presume the problem is all associated with the Analog pin numbers needing to be Arduino compatible :-(

**Comment by fpistm** [comment] 2017-08-17 04:52
Yes, always the same problem... to be or not to be Arduino compatible. :')

**Comment by rogerclarkmelbourne** [comment] 2017-08-17 06:46
Frederic

I'm not sure if its something you can decide...

But given the choice of either being able to use the real Port / Pin name or supporting the Arduino analogue pin number system, I would use Port / Pin 

There are so many other things which are not going to be AVR compatible, that trying to make the Analog pin names compatible will be a minor change compared with the Harvard vs Von Neumann architecture and the size of int and float etc, that people will have to get used to, if migrating from AVR.

**Comment by Adminius** [comment] 2017-08-17 07:13
Pxy/Dx and Ax, deal? :)

**Comment by fpistm** [comment] 2017-08-17 08:52
I will only add possibility to use pin name as an index matching the Dx. (no loop ;))
So Analog will be the same.

PYn == Dx == x for digital
PYn == Ax == x == Dy for analogRead
PYn == Ax == Dy for analogWrite

**Comment by fpistm** [comment] 2017-08-17 12:33
(for Nucleo F429ZI):

**Digital:**
```
digitalWrite(33, HIGH); 
digitalWrite(D33, HIGH);
digitalWrite(PB0, HIGH);
digitalWrite(pinNametoDigitalPin(PB_0), HIGH);
```
**AnalogRead:**
```
analogRead(A0);
analogRead(0);
analogRead(PA3);
analogRead(pinNametoDigitalPin(PA_3));
analogRead(D78);
analogRead(78);
```

**AnalogWrite:**
```
analogWrite(A0);
analogWrite(PA3);
analogWrite(pinNametoDigitalPin(PA_3));
analogWrite(D78);
analogWrite(78);
```
`analogWrite(0);` write on D0 (PG9)

**Comment by rogerclarkmelbourne** [comment] 2017-08-17 23:29
Excellent.

**Comment by fpistm** [comment] 2017-08-18 09:00
PR #83 merged

**Closed by fpistm** 2017-08-18 09:00 UTC
Labels: enhancement
