### ISSUE TITLE
ADC

### ISSUE THREAD

**Issue by CJT1111** [stm32duino/Arduino_Core_STM32#2038] opened 2023-06-12 21:05 UTC
Hello.When will we have a handy variant ADC library available? Like this:
https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/libraries/STM32ADC

**Comment by fpistm** [comment] 2023-06-13 05:53
Hi @CJT1111 
It is a duplicate of #5
Time is always the missing ingredient. It is a community projects, feel free to contribute.
You can also use HAL directly to manage ADC:
https://www.stm32duino.com/viewtopic.php?t=110

**Closed by fpistm** 2023-06-13 05:53 UTC
Labels: Duplicated
