### ISSUE TITLE
STM32G071RB STM32G070RB  uart4 is not invalid

### ISSUE THREAD

**Issue by MINI-Qiang** [stm32duino/Arduino_Core_STM32#1360] opened 2021-04-20 08:31 UTC
**Describe the bug**
STM32G071RB  STM32G070RB  UART4  invalid
uart1,uart2,uart3 normally

**To Reproduce**
Test board: Nucleo-G071RB  

```c++
//HardwareSerial Serial4(PA1,PA0);      // GPIO_AF4_USART4
HardwareSerial Serial4(PC11,PC10);     // GPIO_AF1_USART4
void setup()
{
  Serial4.begin(115200);
}
void loop()
{
  Serial4.println("test");
  delay(1000);
}
``` 

1. Plug
2. Oscilloscope measurement PA0, PC10 output，（Output HIGH, no signal）

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows10]
 - Arduino IDE version: [1.8.12]
 - STM32 core version: [1.9.0]
 - Tools menu settings : nucleo64, NucleoG071RB  , default....
 - Upload method: [STLink]

**Board (please complete the following information):**
 - Name: [e.g. Nucleo G071RB]

**Comment by fpistm** [comment] 2021-04-20 08:35
Duplicate of #1180 and fixed in the master.
New core release 2.0.0 will be released soon. I'm currently doing it.

**Closed by fpistm** 2021-04-20 08:35 UTC
