### ISSUE TITLE
Nucleo STM32F401RE: release 1.9.0 fails, release 1.8.0 succeeds

### ISSUE THREAD

**Issue by rei-vilo** [stm32duino/Arduino_Core_STM32#1205] opened 2020-10-13 11:46 UTC
When reporting any issue, please try to provide all relevant information:

**Describe the bug**

Classic `Blink` sketch built with release 1.9.0 fails to run on Nucleo STM32F401RE.
Same sketch built with release 1.8.0 runs successfully.

**To Reproduce**

1. Launch Arduino IDE
2. Select `Blink` example
3. Select following options

<img width="549" alt="Capture 2020-10-13 à 13 42 14" src="https://user-images.githubusercontent.com/951776/95856179-e8910280-0d59-11eb-99bf-244bdf9a902d.png">

4. Export compiled binary
5. Copy-paste the binary onto the NUCLEO MSD.

**Expected behavior**

LED blinks.

**Screenshots**

See above.

**Desktop (please complete the following information):**

 - OS: [e.g. Windows]
 - Arduino IDE version: 1.8.13
 - STM32 core version: 1.9.0
 - Tools menu settings if not the default: [e.g. Newlib Standard, No Serial] See above
 - Upload method: [e.g. STLink] MSD

**Board (please complete the following information):**

 - Name: Nucleo F401RE
 - Hardware Revision: MB1136 rec.C
 - Extra hardware used if any: none

**Additional context**

Using release 1.8.0 is successful.

Thank you!

**Comment by fpistm** [comment] 2020-10-13 12:35
Hi @rei-vilo 
I close this one as it is a duplicate of  #1206.
Please avoid to open several issue for the same subject, thanks.

**Closed by fpistm** 2020-10-13 12:35 UTC
Labels: Duplicated
