### ISSUE TITLE
CAN protocol

### ISSUE THREAD

**Issue by rsc9421** [stm32duino/Arduino_Core_STM32#1586] opened 2021-12-12 05:02 UTC
hey guys, CAN protocol is not implemented yet, I can implement it using HAL libraries in order to portability with other mcu, if you are interested I will do it.

**Comment by fpistm** [comment] 2021-12-13 08:38
Hi @rsc9421 
This is a community project so do not hesitate to provide it.
Some works have already been done around CAN, see #259.

I close this issue as it is a duplicate of this one.

**Closed by fpistm** 2021-12-13 08:38 UTC
Labels: Duplicated
