### ISSUE TITLE
Arduino SD card library does not work (NUCLEO-L452RE-P)

### ISSUE THREAD

**Issue by Bambofy** [stm32duino/Arduino_Core_STM32#730] opened 2019-10-24 16:37 UTC
I have connected a micro sd card module to the SPI pins on this board at:

SCK - D13 - PB13
MISO - D12 - PB14
MOSI - D11 - PB15
CS - D10 - PA11

However the SD card library does not initialize the sd card. Using the Cardinfo sketch the result is:

> 17:27:24.472 -> Initializing SD card...initialization failed. Things to check:
> 17:27:26.517 -> * is a card inserted?
> 17:27:26.552 -> * is your wiring correct?
> 17:27:26.586 -> * did you change the chipSelect pin to match your shield or module?

The relavent code is as follows:
```C++
// include the SD library:
#include <SPI.h>
#include <SD.h>

// set up variables using the SD utility library functions:
Sd2Card card;
SdVolume volume;
SdFile root;

// change this to match your SD shield or module;
// Arduino Ethernet shield: pin 4
// Adafruit SD shields and modules: pin 10
// Sparkfun SD shield: pin 8
// MKRZero SD: SDCARD_SS_PIN
const int chipSelect = PA11;
void setup() {  
  pinMode(chipSelect, OUTPUT);
  // Open serial communications and wait for port to open:
  Serial.begin(9600);
  Serial.print("\nInitializing SD card...");

  // we'll use the initialization code from the utility libraries
  // since we're just testing if the card is working!
  if (!card.init(SPI_HALF_SPEED, chipSelect)) {
    Serial.println("initialization failed. Things to check:");
    Serial.println("* is a card inserted?");
    Serial.println("* is your wiring correct?");
    Serial.println("* did you change the chipSelect pin to match your shield or module?");

    while (1) {
              digitalWrite(PB13, HIGH);   // turn the LED on (HIGH is the voltage level)
      delay(1000);  
    }
  } else {
    Serial.println("Wiring is correct and a card is present.");

    while (1) {
        digitalWrite(PB13, HIGH);   // turn the LED on (HIGH is the voltage level)
      delay(1000);                       // wait for a second
      digitalWrite(PB13, LOW);    // turn the LED off by making the voltage LOW
      delay(1000);  
    }
  }

  // print the type of card
  Serial.println();
  Serial.print("Card type:         ");
  switch (card.type()) {
    case SD_CARD_TYPE_SD1:
      Serial.println("SD1");
      break;
    case SD_CARD_TYPE_SD2:
      Serial.println("SD2");
      break;
    case SD_CARD_TYPE_SDHC:
      Serial.println("SDHC");
      break;
    default:
      Serial.println("Unknown");
  }

  // Now we will try to open the 'volume'/'partition' - it should be FAT16 or FAT32
  if (!volume.init(card)) {
    Serial.println("Could not find FAT16/FAT32 partition.\nMake sure you've formatted the card");
    while (1);
  }

  Serial.print("Clusters:          ");
  Serial.println(volume.clusterCount());
  Serial.print("Blocks x Cluster:  ");
  Serial.println(volume.blocksPerCluster());

  Serial.print("Total Blocks:      ");
  Serial.println(volume.blocksPerCluster() * volume.clusterCount());
  Serial.println();

  // print the type and size of the first FAT-type volume
  uint32_t volumesize;
  Serial.print("Volume type is:    FAT");
  Serial.println(volume.fatType(), DEC);

  volumesize = volume.blocksPerCluster();    // clusters are collections of blocks
  volumesize *= volume.clusterCount();       // we'll have a lot of clusters
  volumesize /= 2;                           // SD card blocks are always 512 bytes (2 blocks are 1KB)
  Serial.print("Volume size (Kb):  ");
  Serial.println(volumesize);
  Serial.print("Volume size (Mb):  ");
  volumesize /= 1024;
  Serial.println(volumesize);
  Serial.print("Volume size (Gb):  ");
  Serial.println((float)volumesize / 1024.0);

  Serial.println("\nFiles found on the card (name, date and size in bytes): ");
  root.openRoot(volume);

  // list all files in the card with date and size
  root.ls(LS_R | LS_DATE | LS_SIZE);
}
```

**Comment by fpistm** [comment] 2019-10-24 16:48
Hi @Bambofy 
I will check that tomorrow.

**Comment by Bambofy** [comment] 2019-10-24 17:38
> Hi @Bambofy
> I will check that tomorrow.

Thanks 👍

**Comment by fpistm** [comment] 2019-10-25 05:46
Hi @Bambofy 
I've tested and have no error.
So probably wiring issue, SD card (file system, defective, type not supported?)  or something like that.

**Comment by fpistm** [comment] 2019-10-25 07:21
The same than you Nucle-L452RE-P

**Comment by fpistm** [comment] 2019-10-25 07:24
Maybe your shield has a pull up/down resistor on one of the line?

**Comment by Bambofy** [comment] 2019-10-25 07:36
![IMG_20191025_083249](https://user-images.githubusercontent.com/1304898/67552168-6e0f4300-f702-11e9-8df7-7d0a12da67c2.jpg)
![IMG_20191025_083304](https://user-images.githubusercontent.com/1304898/67552213-83846d00-f702-11e9-81cb-4a8a96917e49.jpg)

![IMG_20191025_083446](https://user-images.githubusercontent.com/1304898/67552202-7d8e8c00-f702-11e9-8fee-673402d5e6c4.jpg)

**Comment by Bambofy** [comment] 2019-10-25 07:36
Powweing it through usb port on computer

**Comment by Bambofy** [comment] 2019-10-25 07:56
> 
> 
> ~On your last photo it seems both cable are on GND ??? (Blue and yellow)~
> No this is correct.
> Well I don't know how to help. Did you check all your cable are correct?
> I've tested with 2 SD cards shield without any issue.

ok thank you very much for helping, it must be the sd card i have!

**Comment by Bambofy** [comment] 2019-10-25 08:01
Do i have to change any of the jumpers from the default settings?

**Comment by fpistm** [comment] 2019-10-25 08:03
Sorry to could not help more.

**Comment by fpistm** [comment] 2019-10-25 08:12
> Do i have to change any of the jumpers from the default settings?

No. Did you made hardware modifications? Or in the core?

**Comment by Bambofy** [comment] 2019-10-25 08:20
none

> 
> 
> > Do i have to change any of the jumpers from the default settings?
> 
> No. Did you made hardware modifications? Or in the core?

none, what sd card do you use?

**Comment by fpistm** [comment] 2019-10-25 08:27
If same setup works with a mega then it should work also. Did you enable LTO in the optimisation menu?

**Comment by BennehBoy** [comment] 2019-10-25 08:32
Are you sure this isn't a logic voltage level issue?  There's a voltage
regulator on that SD board, could it be stepping 3.3v down to ~ 2.2v?  I
know this issue has bitten a lot of people in STM32 space previously, I
usually buy non regulated SD boards.

**Comment by fpistm** [comment] 2019-10-25 08:36
Maybe. Don't know.
You can check 5v provided by the board and also check each SPI lines.

**Comment by fpistm** [comment] 2019-10-25 08:44
I will test another SPI device, power the shield with another source (with GND interconnect), check all cables used, try another SPI pins for the boards,...
There is a lot of test which can be performed but you are on your own for this.

**Comment by fpistm** [comment] 2019-10-25 08:48
FYI I used an SDHC of 8GB.

**Comment by Bambofy** [comment] 2019-10-25 10:47
Hi, will test this out today

**Comment by Bambofy** [comment] 2019-10-25 11:11
![javaw_JoeDSJrKqB](https://user-images.githubusercontent.com/1304898/67566837-a02f9d80-f720-11e9-8c1d-3f8627d13917.png)

**Comment by Bambofy** [comment] 2019-10-25 11:24
Got it working!

**Comment by fpistm** [comment] 2019-10-25 12:37
Nice.
Anyway, seems you get an hardware issue on first pin.
did you try to simply toggle the pin to check if they are functional?

**Comment by Bambofy** [comment] 2019-10-25 16:15
> Nice.
> Anyway, seems you get an hardware issue on first pin.
> did you try to simply toggle the pin to check if they are functional?

have not tried testing the pins but i'll check them with a multimeter tomorrow

**Comment by Bambofy** [comment] 2019-10-28 21:14
Hi, turns out that this version of the STM32 chip NUCLEO-L452RE-P is not supported by stm32duino yet.

**Comment by fpistm** [comment] 2019-10-29 04:43
> Hi, turns out that this version of the STM32 chip NUCLEO-L452RE-P is not supported by stm32duino yet.

In the repo it is supported, will be release with 1.8.0.

**Comment by fpistm** [comment] 2019-10-31 13:30
Any update on this ?
I think it could be linked to a voltage issue.
As this board use SMPS per default maybe with this shield you have an issue.
Did you try to power the SD shield with an external source ?

**Comment by fpistm** [comment] 2019-11-05 07:01
@Bambofy 
As mentioned before, I could not reproduce this and probably linked to an hardware issue.
So I close it as I will not be able to help more, I provided some track, hope this help.

**Closed by fpistm** 2019-11-05 07:01 UTC
Labels: Waiting feedback
