### ISSUE TITLE
Hope to add STM32H7 support for STM32 Ethernet library

### ISSUE THREAD

**Issue by q1098401179** [stm32duino/Arduino_Core_STM32#2613] opened 2024-12-24 08:08 UTC
I am currently using STM32Arduino and STM32H750, which cannot drive the built-in ETH function, but STM32F407 is available

**Comment by fpistm** [comment] 2024-12-24 08:52
Duplicate of https://github.com/stm32duino/STM32Ethernet/issues/34

**Closed by fpistm** 2024-12-24 08:52 UTC
Labels: enhancement
