### ISSUE TITLE
macOS issue on uploading since 2.8.0

### ISSUE THREAD

**Issue by gbr1** [stm32duino/Arduino_Core_STM32#2444] opened 2024-07-16 11:52 UTC
**Describe the bug**
When uploading 
```
Sketch uses 26688 bytes (20%) of program storage space. Maximum is 131072 bytes.
Global variables use 1652 bytes (4%) of dynamic memory, leaving 35212 bytes for local variables. Maximum is 36864 bytes.
"" sh "/Users/giovannibruno/Library/Arduino15/packages/STMicroelectronics/tools/STM32Tools/2.2.2/stm32CubeProg.sh" -i swd -f "/private/var/folders/gy/73fdbz8101s04tl73cny05600000gn/T/arduino/sketches/17A24782CF1465DAF7FBC0CC35BFC2D5/service_fw.ino.bin" -o 0x0 
getopt: illegal option -- o
Terminating...
Failed uploading: uploading error: exit status 1
```
**To Reproduce**
Use an STLink attached to any STM32 or DFU.

- Try to flash blink example

**Expected behavior**
It should upload firmware.

**Desktop (please complete the following information):**
 - OS: macOS 14.5
 - Arduino IDE version: 2.3.2
 - STM32 core version: 2.8.0
 - Tools menu settings if not the default: Newlib standard, no serial (not relevant)
 - Upload method: SWD and DFU

**Board (please complete the following information):**
 - Name: G071 with STlink and same behaviour on F411 via DFU

**Additional context**
Impossible to upload the firmware, it seems some option are wrong written

**Comment by fpistm** [comment] 2024-07-16 12:12
Duplicate of: https://github.com/stm32duino/Arduino_Tools/issues/99

**Closed by fpistm** 2024-07-16 12:12 UTC
Labels: duplicate
