### ISSUE TITLE
Nucleo H723ZG, Example-ethernet-*server can't work

### ISSUE THREAD

**Issue by kylongmu** [stm32duino/Arduino_Core_STM32#2527] opened 2024-09-27 05:16 UTC
**Describe the bug**
Example print output: Ethernet shield was not found.  Sorry, can't run without hardware. :(

**To Reproduce**
Just open AdvancedChatServer or WebServer, Upload and run.

**Desktop (please complete the following information):**
 - OS: [Windows11]
 - Arduino IDE version: [2.3.3]
 - STM32 core version: [2.8.1], replaced with git source
 - Tools menu settings if not the default: [default]
 - Upload method: [SWD]

**Board (please complete the following information):**
 - Name: [Nucleo H723ZG]
 - Jumper is default[JP6 ON], without any other connect

**Comment by fpistm** [comment] 2024-09-27 09:11
Hi @kylongmu 
This issue is for STM32Ethernet library and is a duplicate of https://github.com/stm32duino/STM32Ethernet/issues/34

**Closed by fpistm** 2024-09-27 09:11 UTC
